//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradesStudent
    {
        public int IdGradesStudents { get; set; }
        public int IdStudent { get; set; }
        public int IdDiscipline { get; set; }
        public int Grade { get; set; }
        public System.DateTime GradeDate { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Student Student { get; set; }
    }
}
