//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlStudy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ControlStudyEntities : DbContext
    {
        private static ControlStudyEntities _context;

        public ControlStudyEntities()
            : base("name=ControlStudyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public static ControlStudyEntities GetContext()
        {
            if (_context == null)
                _context = new ControlStudyEntities();
            return _context;
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Discipline> Disciplines { get; set; }
        public virtual DbSet<GradesStudent> GradesStudents { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
