//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int IdTeacher { get; set; }
        public string Family { get; set; }
        public string Name { get; set; }
        public string Patronimic { get; set; }
        public int IdDiscipline { get; set; }
        public int IdRole { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Role Role { get; set; }
    }
}
